export const TEXT_CHANGE = 'TEXT_CHANGE';
export const FETCH_REPOSITORY = 'FETCH_REPOSITORY';
export const FETCHREQUEST_SUCCESS = 'FETCHREQUEST_SUCCESS';
export const REQUESTING = 'REQUESTING';
export const FETCHREQUEST_FAILE = 'FETCHREQUEST_SUCCESS';
export const DEFAULT_HEADER = 'DEFAULT_HEADER';